import { useCallback } from "react";
import { UseFormProps, UseFormReturn, useForm } from "react-hook-form";

import { SkylarkObjectFieldInput } from "src/components/inputs";
import { useAIGeneratedFields } from "src/hooks/ai/useAIGeneratedFields";
import { SkylarkObjectMetadataField } from "src/interfaces/skylark";
import { hasProperty } from "src/lib/utils";

export interface AIFieldGeneration {
  isGeneratingAiSuggestions: boolean;
  hasAiSuggestions: boolean;
  formHasValues: boolean;
  populateFieldUsingAiValue: (field: string) => void;
  generateFieldSuggestions: () => void;
  fieldIsAiSuggestion: (field: string) => boolean;
}

export interface UseSkylarkObjectFormWithAutogeneratedValuesReturn
  extends UseFormReturn<Record<string, SkylarkObjectMetadataField>> {
  aiFieldGeneration: AIFieldGeneration;
  formHasObjectValues: boolean;
}

const formHasObjectPropertyValues = (values: object) => {
  const fieldWithValues = Object.entries(values).filter(
    ([key, value]) => !key.startsWith("_") && value !== "",
  );

  return fieldWithValues.length > 0;
};

const getSuggestionForField = (
  suggestions: Record<string, SkylarkObjectMetadataField[]>,
  field: string,
) => {
  const values = suggestions?.[field];
  return values?.[0];
};

export const useSkylarkObjectFormWithAutogeneratedValues = ({
  objectType,
  language,
  onFieldsGenerated,
  formProps,
}: {
  objectType: string;
  language?: string;
  onFieldsGenerated: () => void;
  formProps?: UseFormProps;
}): UseSkylarkObjectFormWithAutogeneratedValuesReturn => {
  const { setValue, getValues, ...form } =
    useForm<Record<string, SkylarkObjectMetadataField>>(formProps);

  const onFieldsGeneratedWrapper = useCallback(
    (
      data: Record<string, SkylarkObjectMetadataField[]>,
      { fieldToFill }: { fieldToFill?: string },
    ) => {
      console.log({ onFieldsGeneratedWrapper: data });
      if (fieldToFill) {
        const value = getSuggestionForField(data, fieldToFill);
        if (value) {
          setValue(fieldToFill, value, {
            shouldTouch: true,
            shouldDirty: true,
          });
        }
      }
      onFieldsGenerated();
    },
    [onFieldsGenerated, setValue],
  );

  const {
    generateFieldValues,
    generatedFieldValues,
    getGeneratedFieldSuggestion,
    isGeneratingAiSuggestions,
  } = useAIGeneratedFields({
    onFieldsGenerated: onFieldsGeneratedWrapper,
  });

  console.log({ isGeneratingAiSuggestions });

  const hasAiSuggestions = Boolean(generatedFieldValues);

  const generateFieldValuesWrapper = useCallback(
    (fieldToFill?: string) => {
      generateFieldValues({
        objectType,
        language: language || (getValues("_language") as string | undefined),
        rootFieldData: getValues(),
        fieldToFill,
      });
    },
    [generateFieldValues, objectType, language, getValues],
  );

  const populateFieldUsingAiValue = useCallback(
    (field: string) => {
      if (!hasAiSuggestions) {
        generateFieldValuesWrapper(field);
        return;
      }

      const value = getGeneratedFieldSuggestion(field, getValues(field));
      if (value !== undefined) {
        setValue(field, value, { shouldTouch: true, shouldDirty: true });
      }
    },
    [
      hasAiSuggestions,
      getGeneratedFieldSuggestion,
      getValues,
      generateFieldValuesWrapper,
      setValue,
    ],
  );

  const formHasObjectValues = formHasObjectPropertyValues(getValues());

  // const fieldHasSuggestions = (field: string) => {
  //   return (
  //     generatedFieldValues
  //       ?.map((obj) => hasProperty(obj, field) && obj[field])
  //       .filter(
  //         (val): val is SkylarkObjectMetadataField => !!val || val === false,
  //       ) || false
  //   );
  // };

  const fieldIsAiSuggestion = useCallback(
    (field: string) => {
      const value = getValues(field);
      const suggestions = generatedFieldValues?.[field];
      return Boolean(suggestions?.includes(value));
    },
    [generatedFieldValues, getValues],
  );

  const aiFieldGeneration: AIFieldGeneration = {
    populateFieldUsingAiValue,
    isGeneratingAiSuggestions,
    generateFieldSuggestions: generateFieldValuesWrapper,
    hasAiSuggestions: Boolean(generatedFieldValues),
    formHasValues: formHasObjectValues,
    fieldIsAiSuggestion,
  };

  return {
    ...form,
    setValue,
    getValues,
    formHasObjectValues,
    aiFieldGeneration,
  };
};
