# While the environment variables for the days sl-develop-10 get updated in Vercel, any deployments are not redeployed.
# Due to this, we want to schedule the skylark-ui production build to be redeployed after the sl-develop-10 instance is deployed.
name: Vercel Deploy Production
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: Environment to redeploy
        options:
          - main
          - beta
  schedule:
    - cron: "00 08 * * 1-5"

jobs:
  trigger-deploy-hook:
    name: Trigger Vercel Deploy Hook
    runs-on: ubuntu-latest
    steps:
      - name: Set deploy hook secret name
        id: set-secret-name
        uses: actions/github-script@v6
        env:
          INPUT_ENVIRONMENT: ${{ github.event.inputs.environment }}
        with:
          result-encoding: string
          script: |
            const inputEnvironment = process.env.INPUT_ENVIRONMENT;
            if(!inputEnvironment) {
              throw new Error("Environment not given")
            }

            if(inputEnvironment === "beta") {
              return "VERCEL_DEPLOY_HOOK_BETA";
            }

            return "VERCEL_DEPLOY_HOOK_MAIN";

      - run: echo "Using GitHub Secret \"${{ steps.set-secret-name.outputs.result }}\""
      - run: curl -X POST ${{ secrets[steps.set-secret-name.outputs.result] }}
