name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  percy-comment-title: Percy Snapshot Comparison
  percy-comment-id: percy-status

jobs:
  build:
    name: Build UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Comment Percy status on PR
        uses: skylark-platform/comment-url-on-pr@v1
        with:
          title: ${{ env.percy-comment-title }}
          comment_id: ${{ env.percy-comment-id }}
          status: building
          github_token: ${{ github.token }}
      - uses: cypress-io/github-action@v4
        with:
          runTests: false
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - run: vercel env pull --yes --environment=development --token=${{ secrets.VERCEL_TOKEN }} .env
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      - run: yarn build
      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: .next

  tests:
    name: Run Cypress Tests
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - uses: actions/checkout@v3
      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: .next
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - run: vercel env pull --yes --environment=development --token=${{ secrets.VERCEL_TOKEN }} .env
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      - name: Load environment variables from .env
        uses: xom9ikk/dotenv@v2
      - name: UI Tests
        uses: cypress-io/github-action@v4
        with:
          start: yarn start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          config-file: cypress.config.ts
          command-prefix: "percy exec --parallel -- npx"
          group: "Skylark UI"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          PERCY_PARALLEL_TOTAL: 2
          # overwrite commit message sent to Dashboard
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          # re-enable PR comment bot
          COMMIT_INFO_SHA: ${{ github.event.pull_request.head.sha }}
