name: Pull Request Checks
on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: pr-checks-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    name: Lint, Prettier & Jest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: yarn
      - run: yarn lint
      - run: yarn prettier:check
      - run: yarn test:ci
      # - name: Upload coverage reports to Codecov with GitHub Action
      #   uses: codecov/codecov-action@v3
      # - name: Test Report
      #   uses: dorny/test-reporter@v1
      #   if: success() || failure()
      #   with:
      #     name: Frontend Unit Test Results
      #     path: "coverage/jest-*.xml"
      #     reporter: jest-junit
      - name: Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: ./coverage
          fail_ci_if_error: true
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

  chromatic-deployment:
    name: Chromatic Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v11
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
